### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by TomasRoj** [AlvarTapia/Arduino_Car_Lib#1]
Hey,

Can you add me to contributors so I can he'll you with development of this library? I think this library has a lot of potential but it needs some changes for example change language to English etc.

Thanks,
Tom

**Comment by AlvarTapia** [comment]
Hi TomasRoj.

Thanks for your suggestion.
This GitHub is meant to hold an Spanish university project.

Once the project is finished, I may translate it and open it for contributors like yourself to expand it.
But, for a couple of months at least, I have to work on it by myself.

I didn't think it would bring any attention, thanks for reaching out and checking the project!
Best regards.
Alvar.

**Comment by AlvarTR** [comment]
Hello TomasRoj.

Sorry for the wait.
As we now have a stable version, I am translating all the libraries to English.
Right now this project is a hobby to me, and the translations are being done in my spare time.

If you are still interested in the project, let me know, and I can make you a collaborator.
Thanks again for checking out this repository, hope to hear from you.
Alvar.

**Comment by TomasRoj** [comment]
I have a lot school nowdays but I can help in my free time. Feel free to add me and we can discuss what you want to help with.

**Comment by AlvarTR** [comment]
Hi TomasRoj.

You are already a collaborator.
I have this as a free time project too.

Right now I don't have any plans for that project, as the Arduino was given to me, and I had to give it back.

The idea with this code is to have a remote that can follow lines, and know in which intersection it has to turn. I don't know how much of that idea is part of the university, but that is basically it.
If you want to expand or divert on that idea, feel free to do it. I will try to translate the code as fast as possible for you to be useful.

Thank you for answering this quickly.

**Comment by TomasRoj** [comment]
Sure! I Will try to expand the idea a bit l have few ideas in my mind. Is it
possible to communicate via other platform like discord or something 
simmilar? It would a lot easier to discuss ideas there.

---------- Původní zpráva ----------
Od: AlvarTR 
Datum: 16. 9. 2020 v 20:58:55
Předmět: Re: [AlvarTapia/Arduino_Car_Lib] Contribution (#1)





Hi TomasRoj.


You are already a collaborator.

I have this as a free time project too.


Right now I don't have any plans for that project, as the Arduino was given 
to me, and I had to give it back.


The idea with this code is to have a remote that can follow lines, and know 
in which intersection it has to turn. I don't know how much of that idea is 
part of the university, but that is basically it.

If you want to expand or divert on that idea, feel free to do it. I will try
to translate the code as fast as possible for you to be useful.


Thank you for answering this quickly.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/AlvarTapia/Arduino_Car_Lib/issues/1#issuecomment-693598237)
, or unsubscribe

**Comment by AlvarTR** [comment]
Sure.

https://discord.gg/t2byhJc
